### PR TITLE
[#8] Fix warnings

### LINKED ISSUE #8: Enable -Wall and cleanup all warnings

### PR DESCRIPTION
**Pull request by vrom911**
Resolves #8

### CODE REVIEW

File: src/Lib/Effects/User.hs [hunk 1]
```diff
@@ -38,7 +40,8 @@ data User = User
 instance ToJSON User
 instance FromJSON User
 
-instance FromField PasswordHash
+instance FromField PasswordHash where
+  fromField f mbs = PwdHash <$> fromField f mbs
```
Comment (ChShersh) [inline src/Lib/Effects/User.hs]: Maybe it's better to use `GeneralizedNewtypeDeriving` and move this instance to `PasswordHas` directly using `deriving`? And also remove `-fno-warn-orpanc` warning from this module.

File: src/Lib/Util/JWT.hs [hunk 2]
```diff
@@ -56,9 +56,8 @@ decodeAndVerifyJWTToken token = do
...
-      Just (now, expiryTimeStatedInToken) ->
-        if expiryTimeStatedInToken < now then
-          Nothing
-        else
-          jwtPayloadFromMap $ JWT.unregisteredClaims claimsSet
+    (,) <$> timeNow <*> JWT.exp claimsSet >>= \(now, expiryTimeStatedInToken) ->
+      if expiryTimeStatedInToken < now then
+        Nothing
+      else
+        jwtPayloadFromMap $ JWT.unregisteredClaims claimsSet
```
Comment (ChShersh) [inline src/Lib/Util/JWT.hs]: I think it's better to rewrite this code using `do`-notation for `Maybe` monad to make it cleaner. Probably putting it under `let` first in order to be able to specify type of this action.

File: src/Lib/Util/JWT.hs [hunk 3]
```diff
@@ -55,10 +55,10 @@ decodeAndVerifyJWTToken :: (MonadIO m, MonadReader AppEnv m) => Text -> m (Maybe
...
-    case (,) <$> timeNow <*> JWT.exp claimsSet of
-      Just (now, expiryTimeStatedInToken) ->
-        if expiryTimeStatedInToken < now then
-          Nothing
-        else
-          jwtPayloadFromMap $ JWT.unregisteredClaims claimsSet
+  pure $ do
+    claimsSet <- JWT.claims <$> JWT.decodeAndVerifySignature secret token
+    (now, expiryTimeStatedInToken) <- (,) <$> timeNow <*> JWT.exp claimsSet
+    if expiryTimeStatedInToken < now then
```
Comment (ChShersh) [inline src/Lib/Util/JWT.hs]: This `if` can be written slightly shorter using [`guard`](https://hackage.haskell.org/package/base-4.11.1.0/docs/Control-Monad.html#v:guard) function instead.

File: three-layer.cabal [hunk 4]
```diff
@@ -25,9 +25,25 @@ source-repository head
...
+      Lib.Effects.Session
+      Lib.Effects.User
+      Lib.Server
+      Lib.Server.Auth
+      Lib.Util.App
+      Lib.Util.JWT
+      Lib.Util.Password
+      Prelude
+  other-modules:
+      Paths_three_layer
```
Comment (ChShersh) [inline three-layer.cabal]: Maybe you could also delete `.cabal` file from this repo?...
